import os
from pathlib import Path

from cryptography.fernet import Fernet
from dotenv.main import load_dotenv


def main():
    """Punto de entrada para Poetry"""
    print("🔒 Generando secrets cifrados...")
    
    # 1. Cargar variables desde .env
    env_path = Path(__file__).parent.parent / ".env"
    load_dotenv(env_path)
    
    secrets = {
        "API_URL": os.getenv("API_URL"),
        "CLIENT_ID": os.getenv("CLIENT_ID"),
        "CLIENT_SECRET": os.getenv("CLIENT_SECRET")
    }
    
    # 2. Validación
    if None in secrets.values():
        missing = [k for k, v in secrets.items() if v is None]
        raise ValueError(f"Missing in .env: {', '.join(missing)}")
    
    # 3. Generar archivo cifrado
    key = Fernet.generate_key()
    cipher = Fernet(key)
    encrypted = {k: cipher.encrypt(v.encode()).decode() for k, v in secrets.items()}
    
    output = f"""# AUTOGENERATED - NO EDIT
from cryptography.fernet import Fernet

_KEY = {key!r}
_SECRETS = {encrypted}

def get_secret(name):
    return Fernet(_KEY).decrypt(_SECRETS[name].encode()).decode()
"""
    # 4. Escribir archivo
    target_dir = Path(__file__).parent.parent / "tek_secrets"
    target_dir.mkdir(exist_ok=True)
    (target_dir / "_secrets.py").write_text(output)
    print(f"✅ Secrets cifrados en {target_dir}/_secrets.py")

if __name__ == "__main__":
    main()